version: "3"
services:
        #  web:
        # image: nginx:latest
        #container_name: web
        #restart: "on-failure"
        # ports:
        # - "6800:80"
        # volumes:
        #- ./nginx/default.conf:/etc/nginx/nginx.conf
  backend:                          
    build:
      context: ./backend 
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "5005:5005"   
    expose:
      - 5005
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
