version: "3"
services:
  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    networks:
      - backend
  client:               
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend   
    networks:
      - backend   
  server:                          
    build:
      dockerfile: Dockerfile.dev
      context: ./backend    
    environment:
      - NODE_PATH=src
      - PORT=5000
      - DB_HOST=mongo
      - DB=test     
    networks:
      - backend  
    depends_on:
      - mongo
    ports:
      - "5000:5000"   
  mongo:
    container_name: mongo
    image: mongo
    ports:
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  data:
    driver: local
